/* Refresh rt_route */
DELETE FROM RT_ROUTE;
UPDATE TR_SECTSTATE SET ROUTE_PROCESS_STATUS = 0;
/* Refresh fl_train */
DELETE FROM FL_TRAIN;
DELETE FROM FL_TRAIN_RECV;
DELETE FROM FL_TRAIN_SEND;
UPDATE TR_SECTSTATE SET FLOW_STATUS = 1 WHERE FLOW_STATUS = 2;